### PR TITLE
API refactor: stage and insert

### PR DESCRIPTION
**Pull request by cantsin**
Builds on #90 

Adds custom API calls for stage and insert, which the UI duly uses. 

Note that there's a minor discrepancy between "stage" and "complete", we should pick one term or the other to keep.

### CODE REVIEW

**Comment by amymok** [comment]
@cantsin which term do you feel that it makes more sense? `stage` or `complete`?

**Comment by cantsin** [comment]
I prefer `complete` myself as that seems more "final", but I'm open to discussion. If we do change the `staged` status then we will need to do a migration. Not a huge problem, just throwing that out there.

**Comment by amymok** [comment]
I don't have a preference here.  As long as we have documentation to support what each phase mean (if there's none right now, let's add them to communicate what each of them mean)

**Comment by cantsin** [comment]
Currently there is no documentation on the various statuses; in fact, I believe one is unused. I'll make a new PR for holistic documentation review -- https://github.com/18F/ReVAL/issues/94 -- soon.

**Review by amymok — APPROVED** [review]
If you want to change everything to complete, feel free to do it here or in another PR.  Other than that, looks good to me.

**Pull request merged**
